### ISSUE TITLE
[BUG] Character Money reset

### ISSUE THREAD

**Issue by Triga307** [qbcore-framework/qb-multicharacter#102]
Having an issues where sometimes peoples money on the main account gets replaced by and alts's account.

**Comment by tom-osborne** [comment]
> Having an issues where sometimes peoples money on the main account gets replaced by and alts's account.


Closing this as not enough information and cannot replicate.

@Triga307 If you notice this happening again, please check client and server consoles for errors and raise a new issue with steps to replicate or evidence of the issue.
