### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Smokezz6969** [qbcore-framework/qb-multicharacter#103]
![unknown (1)](https://user-images.githubusercontent.com/99103156/163897711-166b76e8-fe92-4855-a33f-b1147e5ca5a4.png)

So when i try to use the lastest version of game build i get this error

**Comment by Smokezz6969** [comment]
And i got this error from this line  
model = model ~= nil and tonumber(model) or false
if i disable this i can enter on my server but my skin is default ( gta 5 )

**Comment by dbaizz** [comment]
same issue here, only running on a new reskin.

**Comment by Smokezz6969** [comment]
did you figure it out?

**Comment by tom-osborne** [comment]
> ![unknown (1)](https://user-images.githubusercontent.com/99103156/163897711-166b76e8-fe92-4855-a33f-b1147e5ca5a4.png)
> 
> So when i try to use the lastest version of game build i get this error

Which game build exactly?

**Comment by Z3rio** [comment]
Could not replicate issue
