### ISSUE TITLE
[BUG] Not allowed spaces in Nationality section

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-multicharacter#117]
**Describe the bug**
When typing in a nationality with a space, it doesn't let you, e.g. NZ European or New Zealander

**To Reproduce**
1. Make a new character
2. Enter a nationality with a space in it

**Expected behavior**
Field should allow gaps

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Current
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
Just think it's something that was missed as most of nationalities would be "White", "African-American", "European" etc

**Comment by tom-osborne** [comment]
PR added to address this isue https://github.com/qbcore-framework/qb-multicharacter/pull/122
