### ISSUE TITLE
EPICS new player stuck at characters selection screen

### ISSUE THREAD

**Issue by zulsyazwan** [qbcore-framework/qb-multicharacter#118]
**Describe the bug**
Problem occurs when new player from epics license stuck at characters creation screen

**To Reproduce**
1. Start Fivem
2. Stuck at character creations screen

**Expected behaviour**
Should show the characters selection screen

**Screenshots**
![image](https://user-images.githubusercontent.com/9715088/171422768-97f8dc7c-bd41-4c2c-8dba-9ed9060a2e8d.png)

**Comment by Kingsage311** [comment]
Any errors in the F8 console?
