### ISSUE TITLE
[BUG]stuck on character creation zero errors

### ISSUE THREAD

**Issue by Pandaas-cn** [qbcore-framework/qb-multicharacter#119]
**Describe the bug**
qb-multicharacter can not retrieve player data, it seems that the database returns the result but the front end does not display the selection

**Screenshots**
https://img.guildedcdn.com/ContentMedia/df843f37e82c0d70349de1be1aa3687d-Full.webp?w=651&h=67

**Comment by tom-osborne** [comment]
@Pandaas-cn please could you explain the steps to replicate this? 
What were you trying to do when you got this error?
