### ISSUE TITLE
[BUG] multicharacter didn't load some players characters

### ISSUE THREAD

**Issue by kubax15111** [qbcore-framework/qb-multicharacter#121]
After changing hosting to other one i have problem with multicharacter
![image](https://user-images.githubusercontent.com/67196443/177004773-d5821f74-a65f-4bdd-91c3-e3bba135e76b.png)

**Comment by peppinoita** [comment]
Wrong database configuration

**Comment by tom-osborne** [comment]
> After changing hosting to other one i have problem with multicharacter
Check you installed the database correctly when changing host
