### ISSUE TITLE
[BUG] Non Responsive UI

### ISSUE THREAD

**Issue by TransitNode** [qbcore-framework/qb-multicharacter#125]
![Untitled](https://user-images.githubusercontent.com/56658457/178118319-4647da19-b077-4732-abf0-86d8dd59c20f.png)

Self explanatory, shouldn't even be possible to create a non-responsive ui in 2022.

**Comment by tom-osborne** [comment]
@TransitNode  Is this using the latest version?
Do you see any errors in your client console or server console?

**Comment by tom-osborne** [comment]
@TransitNode I cannot replicate this. Please can you explain the steps you took to get a non-responsive UI?

**Comment by TransitNode** [comment]
I cloned this repo, but this issue has been persistent since the first time I used the public recipe for txAdmin's server deployer. Breaks on every resolution except 1920x1080. No errors in logs or console.

**Comment by tom-osborne** [comment]
@TransitNode Thanks for the information. I tested on 1920x1080 and a smaller resolution. I will test 1280x1080.

Is it immediately unresponsive or does it become unresponsive after certain clicks?

**Comment by TransitNode** [comment]
It's immediately unresponsive, breaks for me on other servers aswell but I can't confirm what versions they are using and what they have modified.

**Comment by tom-osborne** [comment]
> It's immediately unresponsive, breaks for me on other servers aswell but I can't confirm what versions they are using and what they have modified.

Would you be willing to join a discord VC to demonstrate for me? I still cannot replicate this on multiple resolutions
