### ISSUE TITLE
Problem with interior

### ISSUE THREAD

**Issue by iglesiiaskeviin** [qbcore-framework/qb-multicharacter#126]
When changing the spawn position of the character in the multicharacter the interior does not load.

I have tried to change the spawn location of the character to a different place and when I change it the character appears frozen and the interior does not load properly.

**Comment by tom-osborne** [comment]
What did you change exactly?

**Comment by Z3rio** [comment]
Closed, issue is abandoned by creator / he doesnt seem to answer @tom-osborne.
Seems like an issue created by him and not the default issue since it works fine for me and most other people.
