### ISSUE TITLE
qb-multicharacter not support add ped 

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-multicharacter#13]
I already knew this fact
I have tested on many different versions
qb-core not support add ped 
But the question is here
Why not support addition ped to the project
This should be supported
And write documentation about the method of adding
https://imgur.com/acE52lg

https://docs.fivem.net/natives/?_0x389EF71

**Comment by vanillla1** [comment]
Yes, the problem is in the official version
and previous versions
The same problem
@CCasusensa

**Comment by JericoFX** [comment]
make a pr and we can check it.

**Comment by vanillla1** [comment]
Unfortunately with the new update, the same problem
@JericoFX  I didn't understand what you mean by pr
