### ISSUE TITLE
new charater in fivem

### ISSUE THREAD

**Issue by IrishGirlEve** [qbcore-framework/qb-multicharacter#135]
i deleted an old charater and now trying to create a new one it wont let me ive tried uninstalling and reinstalling fivem ive tried clearing cashe the admins have completly removed me from server and nothing fixes it the message that shows up is CrBrowserMain/ FIELDS REQUIRED (@qb-multicharacter/html/script.js:222)

**Comment by tom-osborne** [comment]
It sounds like you are both using an old version and also missing some fields in the character creation form. 

Please update your script and with the latest version you should get some feedback as to what the issue is.
