### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by reduxrp** [qbcore-framework/qb-multicharacter#137]
Hello, do you plan to do multi character on discord role?

**Comment by tom-osborne** [comment]
Hello @reduxrp There is currently no plan to change qb-multicharacter to work with Discord roles. 
What exactly are you expecting to control with a discord role? The number of characters?

**Comment by reduxrp** [comment]
@tom-osborne but if the player will have the Multicharacter I role on discord, he had one extra character

**Comment by JericoFX** [comment]
you can add that to the config with the license
