### ISSUE TITLE
[BUG] Gender displays number, not string

### ISSUE THREAD

**Issue by ihyajb** [qbcore-framework/qb-multicharacter#143]
**Describe the bug**
Throwing this in as an issue so theres a log of it being reported lmao
In the right slide of the UI next to `Gender:` the text for it displays a number, `0` or `1` depending on gender.

**To Reproduce**
1. Use your 👀 

**Expected behavior**
The UI displays `Male` or `Female`

**Screenshots**
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3933343437303837313333333130353637342f313031343231353639343339343538393239342f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/66404074/187548108-8f93d255-7e56-4df1-b89a-cdd891dde25e.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 yes
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 no
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 no

**Additional context**
n/a

**Comment by GhzGarage** [comment]
@ihyajb didn't you know men and women are binary now? Come on guy

**Comment by GhzGarage** [comment]
Fixed
