### ISSUE TITLE
[BUG] Script Error/Models not loading.

### ISSUE THREAD

**Issue by Tragidonious** [qbcore-framework/qb-multicharacter#144]
**Describe the bug**
After restarting the server the ped model no longer shows in the selection screen. If you attempt to select or make a character the game will close.

**To Reproduce**
-Unknown

**Expected behavior**
Upon joining the player model should show in the center allowing the user to either create or continue as a previous character.

**Screenshots**
https://gyazo.com/8e721a845e3eb117b3fdbbfbba009807. 

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 1 day ago.
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] 
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by FaLL3nWhizzy** [comment]
Check if ur clothing packs Have Issue!

**Comment by Tragidonious** [comment]
> Check if ur clothing packs Have Issue!

Ended up having a problem w/ some EUP clothing added, thank you.

**Comment by FaLL3nWhizzy** [comment]
No Probs Man
