### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Miich3** [qbcore-framework/qb-multicharacter#147]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
When either choosing a character or creating a new, scrollbars appear on right side and bottom. Tried 1440p monitor.
**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? [yes many]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
![image](https://user-images.githubusercontent.com/94759971/187776108-e6686de4-5ab8-4a1a-a561-2e764b907aef.png)

**Comment by Z3rio** [comment]
I will try to resolve this today

**Comment by tom-osborne** [comment]
Fixed in #151
