### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by catiagomes94a** [qbcore-framework/qb-multicharacter#150]
**Describe the bug**
The character menu no longer resizes, even when we only enable the creation of one character.

**To Reproduce**
1. Go to 'Config.lua'
2. Put 'Config.DefaultNumberOfCharacters : 1 '
3. When you add the characters again, the name will become large and only have room for 1 character.

**Expected behavior**
I wish it would resize itself as we enable as many characters as we want.

**Screenshots**
![image](https://user-images.githubusercontent.com/72714315/188004270-d780773c-9f36-412c-ba4b-a7f5c7c8ba09.png)

**Questions (please complete the following information):**
 - When you last updated: yesterday
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom?no

**Additional context**
I changed the color of the menu which does not affect this issue

**Comment by Z3rio** [comment]
What should happen in your opinion?
If you switch it to only have 1 slot then it only has 1 slot as it should.
