### ISSUE TITLE
[BUG] Character Not Showing When Selected

### ISSUE THREAD

**Issue by marquisbee** [qbcore-framework/qb-multicharacter#155]
**Describe the bug**
When I goto select my character the preview of my ped doesn't show. When I click "Empty Slot" the default blank ped shows.

This all started happening after I tried to update these with the latest on August 7, 2022:

Updated qb-core resource
Updated qb-multicharacter resource
Updated fivem-appearance resource

**To Reproduce**

1. Update qb-multicharacter
2. Restart server
3. Select already made character from character selection screen

**Expected behavior**

Character should show when selected on character selection screen

**Screenshots**

![multi](https://user-images.githubusercontent.com/105036318/189014915-ae3ddd7c-ce54-42dc-840b-18f5b7164cb1.png)

**Questions (please complete the following information):**

Updated qb-multicharacter, qb-core, fivem-appearance
I am using qb-target
No, I have not renamed any resource other than removing from the end.

**Comment by OfficialRDB** [comment]
Same issue. Could be because of fivem-appearance ?

**Comment by marquisbee** [comment]
> 

I don't think so. I've had the issue before when I updated qb-multicharacter but I forgot how I resolved the issue.

**Comment by Z3rio** [comment]
Works fine for me, although without fivem-appearance.
So I would guess that it has to do with fivem-appearance

**Comment by OfficialRDB** [comment]
https://medal.tv/games/gta-v/clips/BJOIHN7TAMorh/d1337JKA5Tsw?invite=cr-MSxVTHosNzgzNTk5MDUs

I'm up2date with the full QBCore.

**Comment by Z3rio** [comment]
Looks like you have modified qb-multicharacter + as mentioned, this issue is most likely caused by fivem-appearance since you mentioned that you had that installed.

**Comment by marquisbee** [comment]
I've updated fivem-appearance but someone on the discord also said they didn't believe it was that.

**Comment by OfficialRDB** [comment]
> Looks like you have modified qb-multicharacter + as mentioned, this issue is most likely caused by fivem-appearance since you mentioned that you had that installed.

It has nothing to do with fivem-appearance or changing locations to another spot.. I even have it on a clean qbcore install on a dev server.

**Comment by Z3rio** [comment]
Okay mate, well it obviously has something to do with qb-clothing, otherwise I wouldnt say so.
The qb-multicharacter script uses an event from qb-clothing to load the character, which doesnt exist for fivem-appearance.

And as for you @OfficialRDB, I can assure you that you have changed more then just the spawn location since the UI looks quite different from what it looks like by default **OR** you have an old version of the script.

Dont open an issue for help if you arent going to listen to the help you are getting.

**Comment by OfficialRDB** [comment]
> Okay mate, well it obviously has something to do with qb-clothing, otherwise I wouldnt say so. The qb-multicharacter script uses an event from qb-clothing to load the character, which doesnt exist for fivem-appearance.
> 
> And as for you @OfficialRDB, I can assure you that you have changed more then just the spawn location since the UI looks quite different from what it looks like by default **OR** you have an old version of the script.
> 
> Dont open an issue for help if you arent going to listen to the help you are getting. I can assure you that everything works fine on a default server with the newest qb-clothing & qb-multicharacter scripts.

I have a clean installation from 3 weeks ago. Not sure what you on about but the latest updates for the multicharacter was 13 days ago on local files. I never changed qb-clohting and switch to fivem-appearance while I already had the issue.

Please don't think or talk for me next time. Just to make you happen I'll do a clean installation right now, to so you, your wrong.

**Comment by Z3rio** [comment]
> > Okay mate, well it obviously has something to do with qb-clothing, otherwise I wouldnt say so. The qb-multicharacter script uses an event from qb-clothing to load the character, which doesnt exist for fivem-appearance.
> > And as for you @OfficialRDB, I can assure you that you have changed more then just the spawn location since the UI looks quite different from what it looks like by default **OR** you have an old version of the script.
> > Dont open an issue for help if you arent going to listen to the help you are getting. I can assure you that everything works fine on a default server with the newest qb-clothing & qb-multicharacter scripts.
> 
> I don't have a old version running (3 weeks) colors are different and location.
> 
> Alright. Clean installation no issues. removed qb-clothing and replace it with fivem-appearance no issues. Changed location no issues. Changed colors of the qb-multicharacter no issues.
> 
> Need to look and compare the files where it went wrong, or what I'm using that mak this a thing. No sure why you come to at me like that, just cuz I show a video, and tell you it's not fivem-appearance, or a location switch.
> 
> the UI only have different colors. The backend is the same. But anyway I'll do some deeper searching and let people know, if I find the issue.

I'm going to try my best to make this as clear as possible, if you are having issues with the character not spawning then it is caused by qb-clothing, or you not having qb-clothing in the first place.
The spawning of the character is on line 139 of the client file, which uses a qb-clothing event, not having qb-clothing will result in nothing happening.

Other stuff that could cause this is that Config.PedCoords isnt set to the right position or such. 
I'm simply trying to save you time since you will most likely waste your rule out all of these potential issues.

**Comment by OfficialRDB** [comment]
I'm gonna be real honest with you. I compared the files and it looks like fivem-appearance changed something. I have edit my client file of the multicharacter and it works.

I'll leave my client file here, and people can compare and solve their issue.
https://sourceb.in/Kv0pksjbD1

![1](https://user-images.githubusercontent.com/50579206/191748241-dca0e2a8-a839-49c1-8a17-56602b9249cf.PNG)
![2](https://user-images.githubusercontent.com/50579206/191748262-ebac98eb-b7e0-4506-a81a-7d31107cb8a7.PNG)

**Comment by Z3rio** [comment]
> I'm gonna be real honest with you. I compared the files and it looks like something small changed. I have edit my client file of the multicharacter and it works.
> 
> I'll leave my client file here, and people can compare and solve their issue. https://sourceb.in/Kv0pksjbD1
> 
> ![1](https://user-images.githubusercontent.com/50579206/191748241-dca0e2a8-a839-49c1-8a17-56602b9249cf.PNG) ![2](https://user-images.githubusercontent.com/50579206/191748262-ebac98eb-b7e0-4506-a81a-7d31107cb8a7.PNG)

Yeah and that is exactly what I have been trying to tell both of you all this time 😅 
If you are going to use fivem-appearane the default files arent set up for that, which proved to be right since from what I understand you solved it after changing that right?

**Comment by OfficialRDB** [comment]
> 

I followed their documentation when I started using it, but my guess is they changed it. I'm pretty sure the replacement's where not like this.

**Comment by Z3rio** [comment]
Okay, well what I will do is I will go ahead and add support for this natively which should fix this for the future :)

**Comment by ToniSevHD** [comment]
Fix: https://docs.illenium.dev/free-resources/fivem-appearance/multicharacter/qb-core-qb-multicharacter/
