### ISSUE TITLE
[BUG] Stuck on validating characters Screen

### ISSUE THREAD

**Issue by Tamer173** [qbcore-framework/qb-multicharacter#169]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

I just installed a Fresh qbcore server no new script added , started my Server and i am stuck on  Validating Characters

**To Reproduce**
1. Go to 'Fivem'
2. Click on 'Connect'
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

To View my Character Selection UI

**Screenshots**

![e21b8ac4-f819-41c3-aeeb-4f330171a326](https://user-images.githubusercontent.com/105336574/194580944-ffc953c9-5604-41e6-951a-7898b6fcd686.jpg)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Nope
 - Have you renamed `qb-` to something custom? [e.g. yes/no] Nope

**Additional context**

I have also tried to use different version of qb multicharacter avaialble on GitHub they didnt worked for me.

**Comment by BoboTheInsane** [comment]
We are experiencing the same thing, here is the full F8.  Not a fresh server though, just when some people connect they get stuck at "validating characters"  and get these F8 errors
![error1](https://user-images.githubusercontent.com/112822668/194639173-97d718bf-5bc2-4898-a884-716eaf1982ed.png)
![unknown](https://user-images.githubusercontent.com/112822668/194639088-4a02badb-755d-482a-8662-7ba98d68700d.png)

**Comment by mrdennis1212** [comment]
You can try this fix https://github.com/chadreed93/qb-multicharacter/commit/0364e49027dbab306000ff6d876028d0611c3b81

You might also need to change the same lines in qb-spawn tho.

**Comment by Irishstevie** [comment]
This has been fixed and pushed

**Comment by Tamer173** [comment]
Solved the Issue by Updating Both QB-multicharacter and QB-Spawn

**Comment by OkItsTayZr5** [comment]
> Solved the Issue by Updating Both QB-multicharacter and QB-Spawn

can i get the link to both of them
