### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by c00kst3r** [qbcore-framework/qb-multicharacter#171]
Changing Clothes

When i try to change clothes on the ambulance job or police job
it comes up with the items but no character 
when i select clothes it jump back to my player in same clothes as previous
here is a image of console 
![5m](https://user-images.githubusercontent.com/73290866/195118606-8ebe78ee-650c-4e09-a344-9fa213da63bf.jpg)
anyhelp would be greatly appereiated 

c00kst3r

**Comment by JakeHamblin** [comment]
This issue contributes to [this](https://github.com/qbcore-framework/qb-apartments/issues/99) issue. It appears the conversion over to Vue JS has caused some reference error. Bring this back to a revision before the introduction of the new UI results in the apartments working as needed. Someone will likely need to modify the Vue to fix this.

**Comment by Z3rio** [comment]
This issue does not have to do with qb-multicharacter.
Nor does the error have to do with clothing, that error has to do with translations in qb-multicharacter.
