### ISSUE TITLE
[BUG] VueJS Error ("Cannot access viewmodel before initialization")

### ISSUE THREAD

**Issue by JakeHamblin** [qbcore-framework/qb-multicharacter#173]
**Describe the bug**
When loading into the server, a VueJS error appears, causing the user to not be able to actually login. Although they do get the normal prompts, QB-Core isn't properly invoked, causing apartments and other items to not work.

**To Reproduce**
1. Load into server
2. Select character
3. Attempt to enter apartment

**Expected behavior**
User should be able to load into the server, select their character, and QB-Core is properly invoked to store the user state data, allowing QB-Apartments to see that the user is logged in and to know what apartments they own.

**Screenshots**

![](https://i.hambl.in/xhn4zeot.png)

**Questions (please complete the following information):**
 - When you last updated: Current version
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
I went ahead and beautified the VueJS to see where the error is actually being invoked. The VueJS function does properly identify an error and does invoke a warn message. The warn message is invoked here:
```js
J = function(b, a) {
        void 0 === a && (a = ce);
        var c = a ? ae(a) : "";
        q.warnHandler ? q.warnHandler.call(null, b, a, c) : er && !q.silent && console.error("[Vue warn]: ".concat(b).concat(c))
}
```

This error is also directly attributed here:
```js
function dY(a, b, c) {
        if (J("Error in ".concat(c, ': "').concat(a.toString(), '"'), b), h && "undefined" != typeof console) console.error(a);
        else throw a
}
```

The error in question seems to be about the invocation of `viewmodel` before it is initialized. This issue appears to be day-zero and is just getting some real light on it. This is technically a duplicate issue, however, the previous poster didn't follow the template, and doesn't provide any real steps to replicate or troubleshoot.

**Comment by FrequencyRoleplay** [comment]
![char](https://user-images.githubusercontent.com/66968387/197952514-97acff91-36a0-4214-94fb-a5f8542428c9.png)

**Comment by mossywang14** [comment]
Has any fix been found?

**Comment by Z3rio** [comment]
This has been fixed and should probably be closed.
