### ISSUE TITLE
[SUGGESTION] Countries list dropdown

### ISSUE THREAD

**Issue by PedroTeixeira-unP** [qbcore-framework/qb-multicharacter#175]
In the create character option we have the nationality field.
One change I made at the time was to add a dropdown with a list of all countries.

A simple fetch to an api list would give all the countries and make them available for selection.

My suggestion would be to put an option in the config, to get the customizable or non-customizable nationality.
- If it was customizable, i.e. true, the field would remain as it is free to write in.
- If it's false, we would be blocking it to the dropdown of the country list.

**Comment by tom-osborne** [comment]
Nice idea. If you have made the change already, could you raise it as a Pull Request rather than an issue?

**Comment by PedroTeixeira-unP** [comment]
@tom-osborne 
https://github.com/qbcore-framework/qb-multicharacter/pull/176
created, please review and feel free to edit
