### ISSUE TITLE
[SUGGESTION] vue files

### ISSUE THREAD

**Issue by SuperMan-Sam** [qbcore-framework/qb-multicharacter#177]
Can you please post the vue files which before build?
Because the vue.js is builded and simplify. Although it is still modifiable, the simplified code is difficult to easily identify and find.
Please post the files if you can.
Thank you.

**Comment by tom-osborne** [comment]
The javascript is in index.html.

**Comment by SuperMan-Sam** [comment]
> javascript 在 index.html 中。

what does the vue.js for?

> The javascript is in index.html.

**Comment by tom-osborne** [comment]
The vue.js is vie itself.  This is the "vue" framework code required for the page to render.
