### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Exyztence** [qbcore-framework/qb-multicharacter#178]
**Describe the bug**
People on the server at random times (after entering the server or entering qb-clothing) receive other people's playerskin. I think it's a bug on the side of qb-multicharacter, because when I reset the script now, many people reported to me that their skin changed to a different character.

**To Reproduce**
Don't have an idea how to reproduce it, it is completely random

**Expected behavior**
Have their own playerskin

**Screenshots**
**His normal character:** https://media.discordapp.net/attachments/1014557428525834281/1036709738005672046/unknown.png?width=1635&height=910

**After bug**: https://media.discordapp.net/attachments/1014557428525834281/1036707202720878644/unknown.png

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 Newest qb-multicharacter
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 No, just changed style.css of qb-multicharacter, nothing else
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 No

**Comment by Exyztence** [comment]
Okay, so. I was in the menu for choosing my character (qb-multicharacter) and I clicked on another character when the one guy was joining the server and my playerskin changed to his playerskin. I know this guy and know it is his skin

**Comment by Exyztence** [comment]
fixed

**Comment by singh-manavv** [comment]
if this is resolved , we will be closing this thread.
