### ISSUE TITLE
Characters not saving

### ISSUE THREAD

**Issue by GuapDaddy** [qbcore-framework/qb-multicharacter#180]
when some users create characters it is not saving them to the db but it saves them for other users. we have tried reinstalling qb-multicharacter and the issue persisted. we have made no changes to the file yet so not sure why this is happening

**Comment by mazzillinate** [comment]
Have you solved this? I’m having the same issue I can save my character and so can everyone else besides one person and it’s not on his side he’s reset his whole pc. It worked for him for a day and then after we added some scripts like easy admin he cannot save a character. In the logs everyone has a citizen I’d saved besides him

**Comment by joaopedroo5** [comment]
I was having some problems saving characters that didn't had name setup in fivem settings (but midge be because I have special characters in my steam name)

**Comment by Nodeee** [comment]
I am having the same problem :c

**Comment by Spirit-RP** [comment]
Same for me

**Comment by SenticAC** [comment]
> I was having some problems saving characters that didn't had name setup in fivem settings (but midge be because I have special characters in my steam name)

This should not be the problem

**Comment by SenticAC** [comment]
Are you receiving any errors in your server-sided console?

**Comment by Spirit-RP** [comment]
> Are you receiving any errors in your server-sided console?

No error, it may caused by high ping ? There is no error showing.

**Comment by M4lino** [comment]
We are having this issue and have narrowed it down to the FiveM username having special characters in it
