### ISSUE TITLE
auto update qbcore respositories[SUGGESTION]

### ISSUE THREAD

**Issue by underdogminecraft** [qbcore-framework/qb-multicharacter#198]
Do I have to update all the repositories manually by checking github for any updates or it can get update automatically even if i m hosting my server locally.

**Comment by nzkfc** [comment]
For my local I just do a mass pull down using some dum dum .bat file, there is prob a better way to do it, but i've not bothered to learn much github stuff.

1. Make a folder where you want stuff to download to
2. Create a txt file and call it pull-qb-core.bat
3. Inside, just add the repo's you want it to get e.g.:

git clone https://github.com/qbcore-framework/qb-core
git clone https://github.com/qbcore-framework/qb-smallresources
git clone https://github.com/qbcore-framework/qb-<whatever.......>

Then save it and double click it, will start to pull down to that folder.

Someone might come in here and advise of a better way to do it, but it's how I grab stuff for local then dump it into the relevant folders for my resources.
