### ISSUE TITLE
Character stuck on selection screen

### ISSUE THREAD

**Issue by human1104** [qbcore-framework/qb-multicharacter#199]
Hello!

When trying to login into the game, some peoples often stuck into the cselection screen. 

Like this:

https://cdn.discordapp.com/attachments/955238378448781312/1085603690087465031/image.png

But not everybody experienced this problem.  8 peoply tryed my server, and from this 5 people experienced this. One of them cant log in absolutely, one of them restarting game and working, one of them restart ing multiple times, and working. 
F8 dont show any error.  But i tried another multicharacter script, and everybody logged into the server, without any problem. But i would like use this,, but i dont know, how can i solve this problem. 
Anyone can help?

**Comment by Leksap** [comment]
any fix yet
