### ISSUE TITLE
black screen when chosing character 

### ISSUE THREAD

**Issue by HKA417** [qbcore-framework/qb-multicharacter#201]
**Describe the bug**
black screen when chosing character  and getting an error in the console 

**To Reproduce**
[script:qb-multichara] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qb-core/server/player.lua:168: No such export LoadInventory in resource qb-inventory
[script:qb-multichara] > <unknown> (@oxmysql/dist/build.js:22033)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qb-multichara] 
[script:qb-multichara] > handler (@qb-multicharacter/server/main.lua:91)
[script:qb-multichara] > <unknown> (@oxmysql/dist/build.js:22033)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/129807389/230749149-85ed3835-7b13-4a78-a399-f4c95de429f8.png)

**Additional context**

**Comment by amin4tiamo** [comment]
same here

**Comment by Truskii** [comment]
any fix to this

**Comment by chaosninja7** [comment]
still no fix?
