### ISSUE TITLE
[BUG] black screen after spwan ui

### ISSUE THREAD

**Issue by nagy1991** [qbcore-framework/qb-multicharacter#202]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-core/server/player.lua:162: No such export LoadInventory in resource qb-inventory

**Comment by amin4tiamo** [comment]
same thing to me . after updating to qb-inventory latest i was stuck in multichar black screen with this error in live consol :

[script:qb-multichara] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qb-core/server/player.lua:162: No such export LoadInventory in resource qb-inventory

**Comment by Truskii** [comment]
any update on this i got this problem
