### ISSUE TITLE
cannot delete character 

### ISSUE THREAD

**Issue by realtopdat** [qbcore-framework/qb-multicharacter#208]
Something happened and i cant delete my character at the character selection screen. im getting this error.

[      script:oxmysql] Error: qb-core was unable to execute a transaction!
[      script:oxmysql] Table 'zap1002681-2.crypto_transactions' doesn't exist
[      script:oxmysql] DELETE FROM crypto_transactions WHERE citizenid = 'IDB97842'

Please help :(

**Comment by MariusZmr** [comment]
you've deleted the crypto_transaction table from the db
Modify your QBCore scripts if you don't wanna use that feature.

**Comment by IAmDanielPeter** [comment]
Kinda messed up you didn't provide "how" lol

**Comment by Nansjsnnssn2** [comment]
> you've deleted the crypto_transaction table from the db Modify your QBCore scripts if you don't wanna use that feature.

still lookin for the how lmao

**Comment by MariusZmr** [comment]
> > you've deleted the crypto_transaction table from the db Modify your QBCore scripts if you don't wanna use that feature.
> 
> still lookin for the how lmao

Hi, sorry for the your waiting time you spent for the answer...

Remove the crypto variables from the qb-core config.
**QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0 } -- type = startamount - Add or remove money types for your server (for ex. blackmoney = 0), remember once added it will not be removed from the database!
QBConfig.Money.DontAllowMinus = { 'cash', 'crypto' }                -- Money that is not allowed going in minus**

https://github.com/qbcore-framework/qb-core/blob/12eefc35e60f5621fa9e01e192b719732d02ff25/config.lua

I thought you would find out.

**Comment by Nansjsnnssn2** [comment]
> > > you've deleted the crypto_transaction table from the db Modify your QBCore scripts if you don't wanna use that feature.
> > 
> > 
> > still lookin for the how lmao
> 
> Hi, sorry for the your waiting time you spent for the answer...
> 
> Remove the crypto variables from the qb-core config. **QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0 } -- type = startamount - Add or remove money types for your server (for ex. blackmoney = 0), remember once added it will not be removed from the database! QBConfig.Money.DontAllowMinus = { 'cash', 'crypto' } -- Money that is not allowed going in minus**
> 
> https://github.com/qbcore-framework/qb-core/blob/12eefc35e60f5621fa9e01e192b719732d02ff25/config.lua
> 
> I thought you would find out.

would it be the same sort of fix for this: 
![Screenshot 2024-11-28 120849](https://github.com/user-attachments/assets/2a4d9ebc-8c0f-4cd0-a7c7-97a6fe699ccb)

**Comment by MariusZmr** [comment]
> > > > you've deleted the crypto_transaction table from the db Modify your QBCore scripts if you don't wanna use that feature.
> > > 
> > > 
> > > still lookin for the how lmao
> > 
> > 
> > Hi, sorry for the your waiting time you spent for the answer...
> > Remove the crypto variables from the qb-core config. **QBConfig.Money.MoneyTypes = { cash = 500, bank = 5000, crypto = 0 } -- type = startamount - Add or remove money types for your server (for ex. blackmoney = 0), remember once added it will not be removed from the database! QBConfig.Money.DontAllowMinus = { 'cash', 'crypto' } -- Money that is not allowed going in minus**
> > https://github.com/qbcore-framework/qb-core/blob/12eefc35e60f5621fa9e01e192b719732d02ff25/config.lua
> > I thought you would find out.
> 
> would it be the same sort of fix for this: ![Screenshot 2024-11-28 120849](https://private-user-images.githubusercontent.com/178475887/390866189-2a4d9ebc-8c0f-4cd0-a7c7-97a6fe699ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDQ3NjUsIm5iZiI6MTczMzc0NDQ2NSwicGF0aCI6Ii8xNzg0NzU4ODcvMzkwODY2MTg5LTJhNGQ5ZWJjLThjMGYtNGNkMC1hN2M3LTk3YTZmZTY5OWNjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMTQxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDk2MDU3NWI5OGNlNjU4OTU4ODIzYWVhMzQ0OTRiYjJlOTQ2OTdkYzEwZmZkMGUwMGFiZjY4ZGI1ZGEyYTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HqU9_AKeKcZ890YnKkZYJMdpI2ocdQPTszRH8wqcP3k)

Seems like you don't have the column 'citizenid' in that table called 'phone_messages'
