### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by itzzjd123** [qbcore-framework/qb-multicharacter#217]
SCRIPT ERROR: @qb-multicharacter/server/main.lua:99 attempt to index a nil value
> rawQuery (@oxmysql/dist/build.js25045)
> processTicksandRejections (node:internal/process/task_queues:96)

Anyone know what this means at all?? I haven't touched the file or anything so i am not sure what to do???

**Comment by BKunlmtd** [comment]
Same issue here.

**Comment by knightofmercs** [comment]
any fix for this? unsure what to do with it
