### ISSUE TITLE
[BUG] My In-game Username 

### ISSUE THREAD

**Issue by PheOnXz** [qbcore-framework/qb-multicharacter#218]
Iam Getting An Issue That I have Made A Server 
And It's running Smoothly for Me But The Problem Is That The In-game Username is Showing My Desktop Username (Sufyan)
So then I changed my desktop username 😭 but still it's showing 😕 (Sufyan) my previous Username 
Please Help Me Out

**Comment by WarumDach** [comment]
Launch steam before FiveM
