### ISSUE TITLE
script error: @qb-multicharacter line 118

### ISSUE THREAD

**Issue by ndshadowz** [qbcore-framework/qb-multicharacter#230]
I am having an issue with qb-multicharacter where once I attempt to load my character, the screen cuts to black like it will load into the city to select a spawn location, but then it stays black indefinitely. Here is the actual code that pops up on the live console:

SCRIPT ERROR: @qb-multicharacter/server/main.lua:118: attempt to call a nil value (field 'Login')
> handler (@qb-multicharacter/server/main.lua:118)

![Capture|690x33](upload://4f1HkDNJBVGNgmSjQ66PRUohErv.png)

Please Help! No One Can Load In!

**Comment by Nelsonic1990** [comment]
I'm also having this issue although mine is on line 120, was working fine until I installed a police script, and all of its dependencies, but none of them have any link, or bearing on qb_multicharacter
