### ISSUE TITLE
[ERROR]Please help me for SCRIPT ERROR: @qb-multicharacter

### ISSUE THREAD

**Issue by MakoCEO** [qbcore-framework/qb-multicharacter#235]
Hello
The following error keeps appearing on the console, but it does not go away even after updating qb-multicharacter.
Could you please tell me the solution?

[      script:qb-core] [qb-core:LOG] Jelly PLAYER SAVED!
[script:qb-multichara] [qb-core] Jelly (Citizen ID: CCX05018) has successfully loaded!
[script:qb-multichara] SCRIPT ERROR: @qb-multicharacter/server/main.lua:109: attempt to index a nil value
[script:qb-multichara] > rawQuery (@oxmysql/dist/build.js:25047)
[script:qb-multichara] > runMicrotasks (<anonymous>:0)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by LandoGitHubDotCom** [comment]
Same problem here.

**Comment by bhager429** [comment]
no info on this. having the same problem.

**Comment by sarangcr03** [comment]
Its an issue with discord permissions, you can fix it by allowing FiveM access to discord on the client machine. Here is the relevent line in main.lua. 
```TriggerEvent("qb-log:server:CreateLog", "joinleave", "Loaded", "green", "**".. GetPlayerName(src) .. "** (<@"..(QBCore.Functions.GetIdentifier(src, 'discord'):gsub("discord:", "") or "unknown").."> |  ||"  ..(QBCore.Functions.GetIdentifier(src, 'ip') or 'undefined') ..  "|| | " ..(QBCore.Functions.GetIdentifier(src, 'license') or 'undefined') .." | " ..cData.citizenid.." | "..src..") loaded..")```

**Comment by rxnm** [comment]
> Its an issue with discord permissions, you can fix it by allowing FiveM access to discord on the client machine. Here is the relevent line in main.lua. `TriggerEvent("qb-log:server:CreateLog", "joinleave", "Loaded", "green", "**".. GetPlayerName(src) .. "** (<@"..(QBCore.Functions.GetIdentifier(src, 'discord'):gsub("discord:", "") or "unknown").."> | ||" ..(QBCore.Functions.GetIdentifier(src, 'ip') or 'undefined') .. "|| | " ..(QBCore.Functions.GetIdentifier(src, 'license') or 'undefined') .." | " ..cData.citizenid.." | "..src..") loaded..")`

How exactly to fix it then please? I am having the same issue. I have the above code, but how to allow it access to discord as you say? thanks.

**Comment by ChiChixxTrigga** [comment]
Anything on a fix for this error?

**Comment by Bobbbe** [comment]
just comment line in qb-multicharacter/server/main.lua    --   TriggerEvent("qb-log:server:CreateLog", "joinleave", "Loaded", "green", "**".. GetPlayerName(src) .. "** (<@"..(QBCore.Functions.GetIdentifier(src, 'discord'):gsub("discord:", "") or "unknown").."> |  ||"  ..(QBCore.Functions.GetIdentifier(src, 'ip') or 'undefined') ..  "|| | " ..(QBCore.Functions.GetIdentifier(src, 'license') or 'undefined') .." | " ..cData.citizenid.." | "..src..") loaded..")

**Comment by musictomy** [comment]
> just comment line in qb-multicharacter/server/main.lua -- TriggerEvent("qb-log:server:CreateLog", "joinleave", "Loaded", "green", "**".. GetPlayerName(src) .. "** (<@"..(QBCore.Functions.GetIdentifier(src, 'discord'):gsub("discord:", "") or "unknown").."> | ||" ..(QBCore.Functions.GetIdentifier(src, 'ip') or 'undefined') .. "|| | " ..(QBCore.Functions.GetIdentifier(src, 'license') or 'undefined') .." | " ..cData.citizenid.." | "..src..") loaded..")

Yep

 that worked for me thanks

**Comment by FnTioHard** [comment]
Vlw galera vcs são fodas !
