### ISSUE TITLE
[BUG] character selection

### ISSUE THREAD

**Issue by TheTracker0** [qbcore-framework/qb-multicharacter#243]
**Describe the bug**
I don't have the character selection interface, I spawn with a png in a random place on the map.

**To Reproduce**
Connect to the server

**Screenshots**
![image](https://github.com/qbcore-framework/qb-multicharacter/assets/72630277/993d6aa3-44bb-412e-86a8-c51b599a3056)

**Comment by TheTracker0** [comment]
> Hi was just wondering if you had found anyway on fixing this issue as i am having the same

No, I will try to reinstall Windows

**Comment by planky1111111** [comment]
why would you reinstall windows

**Comment by TheTracker0** [comment]
> why would you reinstall windows

I have tried everything, the developer of the server I have the issue with tell me to do it
