### ISSUE TITLE
[BUG] Not sure if bug but keep getting this

### ISSUE THREAD

**Issue by musictomy** [qbcore-framework/qb-multicharacter#248]
**Describe the bug**
after logging in txadmin reports this on my localhost:

[script:qb-multichara] SCRIPT ERROR: @qb-multicharacter/server/main.lua:108: attempt to index a nil value

![multi](https://github.com/qbcore-framework/qb-multicharacter/assets/8762957/dc91c616-37b0-4983-b58d-4e427e3e9a41)

**Comment by WPinzonDev** [comment]
Do you have any custom scripts or have you made any changes to qb-multicharacter?

**Comment by musictomy** [comment]
I have [illenium-appearance
(https://github.com/iLLeniumStudios/illenium-appearance) installed

So I get this:

[      script:hardcap] Connecting: RR-GB
[      script:qb-core] [qb-core:LOG] RR-GB PLAYER SAVED!
[script:qb-multichara] [qb-core] RR-GB (Citizen ID: xxxx) has successfully loaded!
[script:qb-multichara] SCRIPT ERROR: @qb-multicharacter/server/main.lua:108: attempt to index a nil value
[script:qb-multichara] > rawQuery (@oxmysql/dist/build.js:26449)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)
[ citizen-server-impl] server thread hitch warning: timer interval of 156 milliseconds
[      script:qb-core] [qb-core:LOG] RR-GB PLAYER SAVED!
[      script:qb-core] [qb-core:LOG] RR-GB PLAYER SAVED!
[      script:qb-core] [qb-core:LOG] RR-GB PLAYER SAVED!

**Comment by musictomy** [comment]
I just commented out the line in Multicharacter as I dont use qb-inventory (unless I could of done it a diffrentway)

`--exports['qb-inventory']:AddItem(src, v.item, v.amount, false, info, 'qb-multicharacter:GiveStarterItems')`
