### ISSUE TITLE
[BUG] SkipSelection Spawn

### ISSUE THREAD

**Issue by WPinzonDev** [qbcore-framework/qb-multicharacter#249]
Describe the bug
When setting Config.SkipSelection to true in the config.lua file of qb-multicharacter, an error occurs when trying to load a previously created character. After closing the game (without closing the server) and trying to load the character again, the screen stays black with a "loading" indicator in the bottom right corner that never goes away, preventing the character from loading properly.

To Reproduce

Go to the config.lua file in qb-multicharacter.
Set Config.SkipSelection to true.
Start the game and create a character.
Close the game (but not the server).
Restart the game and try to load the previously created character.
See the error: the screen stays black with a "loading" indicator in the bottom right corner that never disappears.
Expected behavior
The expected behavior is that when loading a previously created character with Config.SkipSelection set to true, the character should load correctly without the screen staying black and without the "loading" indicator being eternal.

Screenshots:
![Sin título](https://github.com/qbcore-framework/qb-multicharacter/assets/37649098/a15f524f-f13e-4b4e-9838-df3120b2c914)

Questions:

When you last updated: I have been testing for several days and the last test was today.
Are you using custom resource? which ones? No, I am only using qb-multicharacter, nothing custom.
Have you renamed qb- to something custom? No.
Additional context
I have noticed that the issue seems to be related to setting Config.SkipSelection to true, as the problem does not occur when it is set to false and characters load correctly. This suggests that there is a specific bug with the SkipSelection functionality.

**Comment by d56Wr** [comment]
Confirm, same thing happens on my server. It took me way too long to find that bug :(

**Comment by RichardGrant-93** [comment]
I added a print inside qb-multicharacter:client:spawnLastLocation does not seem to ever be getting called.

**Comment by djz3r0** [comment]
@SukiTibi I'm struggling with the same issue.
Couldn't figure out where to place it in the fxmanifest.lua yet.
Can you give a snippet?

**Comment by asapverneri** [comment]
> I added a print inside qb-multicharacter:client:spawnLastLocation does not seem to ever be getting called.

wanna share?

**Comment by SukiTibi** [comment]
> @SukiTibi I'm struggling with the same issue. Couldn't figure out where to place it in the fxmanifest.lua yet. Can you give a snippet?

`fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'qb-inventory'
description 'qb-multicharacter Allows players to create characters'
version '1.0.4'

shared_scripts {
    '@qb-core/shared/locale.lua',
    'locales/en.lua',
    'locales/*.lua',
    'config.lua',
    '@ox_lib/init.lua', ----- You need to place here
}

client_scripts {
    'client/main.lua'
}


server_scripts  {
    '@oxmysql/lib/MySQL.lua',
    'server/main.lua'
}

ui_page 'html/index.html'

files {
    'html/image/*.png',
    'html/image/*.gif',
    "html/js/*",
    'html/index.html',
    'html/css/*',
}

dependencies {
    'qb-core',
    'qb-spawn'
}`

**Comment by SukiTibi** [comment]
```
shared_scripts {
    '@qb-core/shared/locale.lua',
    'locales/en.lua',
    'locales/*.lua',
    'config.lua',
    '@ox_lib/init.lua', --Add this
}
```

**Comment by Pyth3rEx** [comment]
still an issue

**Comment by Aprileen** [comment]
still a problem...
