### ISSUE TITLE
problem add custem ped

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-multicharacter#25]
What is the cause of the problem?
when added new ped from gta5-mods
https://i.imgur.com/0LV0iCX.png
charPed = CreatePed(2, model, Config.PedCoords.x, Config.PedCoords.y, Config.PedCoords.z - 0.98, Config.PedCoords.w, false, true)

old issues
https://github.com/qbcore-framework/qb-multicharacter/issues/13

**Comment by vanillla1** [comment]
@GhzGarage this is fresh copy for qbcore

**Comment by darknight2590** [comment]
This was tested and I have the same problem
ped does not appear in qb-multicharacter
There seems to be a problem with native
I will try to solve the problem and send an update

**Comment by evanillaa** [comment]
There is no solution ?

**Comment by darknight2590** [comment]
I have tried the latest update and the problem is not fixed
