### ISSUE TITLE
Why is /logout hard-coded to "admin"?

### ISSUE THREAD

**Issue by Jamesking56** [qbcore-framework/qb-multicharacter#251]
Why is `/logout` hard-coded to only allow admins to run? Is it something normal users shouldn't have access to?

I suggest changing this to its own unique ace permission instead so it can be customised who has access.

https://github.com/qbcore-framework/qb-multicharacter/blob/4ac9714dace30988fd33c792412c513b30cd758e/server/main.lua#L61-L65

**Comment by brandon1808** [comment]
@Jamesking56 on line 65 just change it from admin to user and /logout will be used for everyone

**Comment by brandon1808** [comment]
Issues is sloved
