### ISSUE TITLE
stuck on character creation zero errors

### ISSUE THREAD

**Issue by CaseIRL** [qbcore-framework/qb-multicharacter#33]
Pretty much as title says. 

Have been getting stuck on this same screen everytime can't load in.

Have tried reverting the multicharacter back to steamID and added steam into players -- didnt work
Reverted it back to regular -- didnt work
Downloaded fresh from repo instead of txadmin depoly -- didnt work
Fresh SQL fresh MC -- didnt work

Checked all SQL connection info is all accurate and SQL was installed with no errors twice. 

I'm kind of puzzled for ideas here when i'm getting literally ZERO errors anywhere (I mean that also... none xD)

Any help would be greatly appreciated <3

![image](https://user-images.githubusercontent.com/90377400/132648195-85ed04d0-41b0-426c-9575-64b69667bee3.png)

**Comment by GhzGarage** [comment]
discord.gg/qbcore
