### ISSUE TITLE
[BUG] Character isn't getting updated when loging out of city. 

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-multicharacter#46]
So i updated my server about 4-5 days ago and now it have seem that none of my character data is being save after loging out. i have made a post about this in the qb-core cause i wasn't sure which one was the right area and i aspect it to be address. i Post this Video about my issue https://youtu.be/Y5veb0DDCyo ..
I havent had any issue up until i got this latest update and it has been like 3 days since i was told about this issue and its still not fix.
Can i get some support plz

**Comment by GhzGarage** [comment]
You don’t have onesync infinity on or you don’t have an updated players database table. All of the required changes are in the discord

**Comment by Kromanic** [comment]
i cant get into the discord dosen't let me connect for some reason

**Comment by JericoFX** [comment]
no, the bot remove people who has been in leaks servers

**Comment by Kromanic** [comment]
if i remove all of the leak server would it let me in ?

**Comment by JericoFX** [comment]
you need to appeal that, go here https://discord.gg/jeFeDRasfs and follow the guide
