### ISSUE TITLE
[BUG] when adding new ped for qbcore

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-multicharacter#50]
**Describe the bug**
Hello, the problem is frequent with many users
It is when you add a new PED 
problems appear in fivem natives
The problem appears with older versions
And new versions of the project Unresolved

**Expected behavior**
When adding a custom ped

**Screenshots**
https://ibb.co/whTjKkw
and more link for problem
https://forum.cfx.re/t/qbcore-error-with-ped/4750818
https://github.com/qbcore-framework/qb-multicharacter/issues/25
https://github.com/qbcore-framework/qb-core/issues/210
Discord server can be checked
There are many problems with this

**Questions (please complete the following information):**
 - When you last updated: [yesterday]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
The problem is with the qb-multicharacter not loading ped
https://docs.fivem.net/natives/?_0x389EF71
I have add new ped with other projects  esx and vrp And it was working fine

**Comment by ZZG994521** [comment]
Hello, I am using the qb-clothing script, this is what happened when I tried to change the PED face and hairstyle:https://cdn.discordapp.com/attachments/841605043479773204/894514279716376577/20211003174838_1_2_LI.jpg

**Comment by ZZG994521** [comment]
I really don't know how to solve this problem
