### ISSUE TITLE
[BUG] liberty city

### ISSUE THREAD

**Issue by Zviux** [qbcore-framework/qb-multicharacter#65]
![image](https://user-images.githubusercontent.com/92739528/144240438-15b3664b-b270-49f4-8e7a-e6b39636521f.png)
it comes when i log in, only when i activate liberty city

**Comment by izMystic** [comment]
not a bug

**Comment by izMystic** [comment]
Just remove line 77-81, since liberty map doesn't have actual "interiors"

**Comment by Zviux** [comment]
thanks its helped
