### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Iamozzyy** [qbcore-framework/qb-multicharacter#66]
Just an issue,
Im currently updating to the newer qb-core. I have one issue when creating a character. 
When putting in name, dob, nationality and confirm im stuck in a black screen with a spinning loading sign bottom right corner.
I have no errors in consoles. F8. Etc 
Im not to sure what is causing this but when removed i can load in.

**Comment by iBrian2** [comment]
Why do they close tickets that arent even solved....
