### ISSUE TITLE
Multichar Not Loading [BUG]

### ISSUE THREAD

**Issue by QuakeAcid** [qbcore-framework/qb-multicharacter#68]
**Describe the bug**
anyone know why some players would get stuck right before the character select(the blurry screen right before the UI slides in), they have to delete their cache every time before they join and for some even that doesn't help?

Most of the time from what i've gathered the ones that have this problem have bad hardware.

**To Reproduce**
- Try to join the server

**Expected behavior**
- The Character select UI should load in

**Screenshots**
Have had this error for a long time, maybe it could be related?
https://i.imgur.com/OdklSWe.png

**Questions (please complete the following information):**
 - When you last updated: i keep the server updated according to the change-log on discord
 - Are you using custom resource? which ones? everything Multichar related is default
 - Have you renamed `qb-` to something custom? No

**Comment by QuakeAcid** [comment]
Edit: for some reason some of them have this issue when they are connected in a discord call

**Comment by NegraLyda** [comment]
Same problem. Sometimes needs to restart script 5-6 times.

**Comment by solracxoxo** [comment]
i also got this problem i hope we can find a fix

**Comment by Netkiriya** [comment]
I know this is an issue from a couple years ago but the exact same thing is happening in my FiveM server to about 10 people the past week, and we've had ZERO luck. Was there a fix for this by chance

**Comment by Adonislee94** [comment]
i am having the same issue, someone please post fix
