### ISSUE TITLE
Character not loading [BUG]

### ISSUE THREAD

**Issue by doratheexplorer123** [qbcore-framework/qb-multicharacter#70]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
connecting to the server and having a blurry screen and not loading their characters
![unknown](https://user-images.githubusercontent.com/95997843/145704228-b59673c2-b2e6-4292-9676-7b76c318585c.png)

**Expected behavior**
loading to the server and showing up their characters/create character screen

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: never updated anything except multichar and spawn after all the issues and never fixed it
 - Are you using custom resource? which ones? nope
 - Have you renamed `qb-` to something custom? nope

**Additional context**
things I've done
-connect and create a fivem ID
-connect steam and change steam account
-close discord (reopen discord)
-restart PC
-restart server for almost 10 times
-clear cache both (server/client)
-update qbmultichar and qbspawn 
-removed whitelisting
-remove antivirus and remove firewall
-tried to connect to different qbcore servers and same thing happens

**Comment by Squizy1722** [comment]
I maybe have something for you its not tested so let me know if it is working:
[Go To qb-multicharacter -> client -> main.lua]
In the first lines you see this code:
```
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		if NetworkIsSessionStarted() then
			TriggerEvent('qb-multicharacter:client:chooseChar')
			return
		end
	end
end)
```
**Change the Citizen.Wait(0) to Citizen.Wait(5000)**
So it will look like this:
```
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(5000)
		if NetworkIsSessionStarted() then
			TriggerEvent('qb-multicharacter:client:chooseChar')
			return
		end
	end
end)
```
