### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SahapYT** [qbcore-framework/qb-multicharacter#73]
I restet my database and when i try to make new character error cames
pic: https://imgur.com/a/qLEp1WF

**Comment by DevDokus** [comment]
I have a similar problem. All plugins with without any errors 👏 
but the moment we enable multicharacters we get the following error.
![image](https://user-images.githubusercontent.com/49053928/150038009-73eeb9a4-3af2-4338-b0ea-93e89f83c40a.png)

The database is inserted and empty, character is not made and you stay in a infinite black loading screen

**Comment by Mryococo91** [comment]
I had this problem and updated the **oxmysql** script [https://github.com/overextended/oxmysql/releases/tag/v1.9.3](url)

**Comment by ItsANoBrainer** [comment]
Update your core multicharacter and oxmysql
