### ISSUE TITLE
[SUGGESTION] add an admin command

### ISSUE THREAD

**Issue by Mryococo91** [qbcore-framework/qb-multicharacter#76]
**Is your feature request related to a problem? Please describe.**
I noticed that you can't delete the character of a player in admin

**Describe the feature you'd like**
I would like to have a command to delete a player's character. for example, in a roleplay server, the player's character deserves an RP death. we can say that the player in question will delete his character, but there may be people who will not do it because of divert reason

Also, it would be nice to have an option in the configuration to replace the delete button with a delete request, if possible the request would be a webhook discord. This would prevent people from creating 15 characters in the same day.

**Comment by Z3rio** [comment]
This issue should now be resolved after pushing these two PR's:
https://github.com/qbcore-framework/qb-core/pull/815
https://github.com/qbcore-framework/qb-multicharacter/pull/141

**Comment by Z3rio** [comment]
This issue is now fully fixed and implemented!
