### ISSUE TITLE
[BUG] Won't allow the use of name "Michelle"

### ISSUE THREAD

**Issue by MaximusR9** [qbcore-framework/qb-multicharacter#79]
**Describe the bug**
Create a new character with name `Michelle` and you will get error in the f8 console

**To Reproduce**
1. Go to the Character Selection screen
2. Click on Create New Character
3. Enter firstname: `Michelle` and then enter any lastname/nationality/date of birth.
4. Press f8 to see the error

**Expected behavior**
Should allow the use of the word Michelle

**Screenshots**
<img width="282" alt="image" src="https://user-images.githubusercontent.com/49029210/151676514-f79ad2e4-e798-429f-bdd0-fa62af425ed6.png">

**Questions (please complete the following information):**
 - When you last updated: Yesterday
 - Are you using custom resource? which ones? No custom resources
 - Have you renamed `qb-` to something custom? No

**Comment by AnDylek** [comment]
> 

Your first name contains **bad word** (Mis**hell**e) that is set in profanity filter. 
You can remove word "hell" from list and name Michelle should be allowed.
List of badwords is located in **html/profanity.js**

**Comment by MaximusR9** [comment]
> > 
> 
> Your first name contains **bad word** that is set in profanity filter. You can remove word `hell` from the list and name Michelle should be allowed. List of badwords is located in **html/profanity.js**

The thing is it should detect the word "Hell" as the bad word not the whole "Michelle" word, this way if anyone used any name that contains the word Hell or any other word that's in the profanity filter it will simply not allow that name to be used.

Here's another thing, what if I want to keep the word Hell in profanity file but also want that user should be able to use the name Michelle? That simply won't work.
