### ISSUE TITLE
[SUGGESTION] - MultiCharacter for admin only

### ISSUE THREAD

**Issue by gorthaur3019** [qbcore-framework/qb-multicharacter#81]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the nature of the problem.

For now everyone can create multiple characters

**Describe the feature you want**
A clear and concise description of what you want to happen. and in as much detail as possible how it would work in your opinion. Please try to keep it unique.

Make the creation of several characters possible only for people whitelist example of admin or moderator on the server

**Describe the alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered for people to have in mind in case the main idea is not liked but a derivative is.

For RP servers we want to limit character creation for our players, one per person except for admins who can create more.

**Comment by iktray** [comment]
#78

**Comment by tom-osborne** [comment]
This feature exists. 

To achieve your request, you can set the config option `Config.DefaultNumberOfCharacters = 1` and then add your admins licences into the config option `Config.PlayersNumberOfCharacters` as follows: -

```lua
Config.PlayersNumberOfCharacters = { -- Define maximum amount of player characters by rockstar license (you can find this license in your server's database in the player table)
    { license = "license:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", numberOfChars = 2 },
}
```
