### ISSUE TITLE
[BUG] [MAJOR] "No Starting Apartment" Parameter Doesn't Work, Resets Character and Forces Apartment.

### ISSUE THREAD

**Issue by ch0sguy** [qbcore-framework/qb-multicharacter#83]
**Describe the bug**
When editing the config modifier of "starting apartments" to "false", it only works for the first instance when a player joins; if they relog and attempt to select the same character they just modified, it will prompt the "select apartment" screen instead of the "spawn" menu, and force one to restart their customization, essentially wiping the character.

**To Reproduce**
Enter config and swap "Starting apartment" to false, reload your server, launch the game, and make a new character.
Finish customizing and confirm, then, exit the game (even relaunch your server for a secondary measure), join, an reselect said character; the server will then prompt you to "select an apartment" instead of "spawn", forcing you into an apartment, resetting your customized character, and essentially reverts to starting apartments being set to false.

**Expected behavior**
Player data should be effectively saved regardless of whether the server chooses to enable starting apartments or not, it seems as if the server only saves the "first time character" parameters if they are given an apartment for what ever reason.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] As of 2/27/2022, fresh install, similar issue on previous version, however (fresh qb-clothing addition as well).
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Quite a few, including qb-target, but not sure how they would effect this process.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No.

**Comment by izMystic** [comment]
did you also turn it off in qb-apartments?
