### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kaidenkhant** [qbcore-framework/qb-multicharacter#97]
**Describe the bug**
Creating a character and then setting it up in the first character creation menu (looks of the character and clothes) then once I'm out of the starting apartment - I relog. Once I relog into the server, the character is invisible on the multicharacter screen AS WELL AS when I'm loaded into the server. Other people can see me but I cannot see myself. At first it was only happening for me but later, it started happening for others (assuming because they haven't relog for the first time after creating their character)

This all started happening after I tried to update these with the latest on March 30, 2022:

- Updated qb-core resource
- Updated qb-clothing resource
- Removed qb-bossmenu and added qb-management (as well as ran the SQL)

**To Reproduce**
1. First, make sure you've got the latest qb-core & qb-clothing
2. Then create your character and customize it.
3. Once done creating and loaded into the city streets, disconnect and relog into the server.
4. I don't see any error on F8 Console or Server Console but you should be able to see your saved character has become invisible.

**Expected behavior**
Expected it to be normal and not be invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/64560839/161118540-a8af151b-1dcd-4c4d-9996-139d09821209.png)

**Questions (please complete the following information):**
 - Updated qb-multicharacter last week, however, updated qb-core, qb-clothing yesterday.
 - okokChatV2 was added yesterday too but nothing else has caused any issue before.
 - No, I have not renamed any resource other than removing "-main" from the end.

**Additional context**
Was told by treyyy to make this bug report as we both think it has something to do with qb-multicharacter. If not, I apologize but I hope to get this fixed soon as it's pretty major to not be able to see your own character.

**Comment by IngPleb** [comment]
My friend had experienced something similar, in his case he just deleted his fivem cache and joined back. Everything worked normally.

Have you tried cleaning your fivem cache?

**Comment by marquisbee** [comment]
I'm also having this issue. I've deleted my server cache, FiveM cache and still nothing. Before I delete my cache we were being show default ped but now the spot I should be standing is empty.

**Comment by Z3rio** [comment]
Could not replicate issue

**Comment by OfficialRDB** [comment]
I'm having this issue too. Tried to empty my data cache but without luck.
https://medal.tv/games/gta-v/clips/BJOIHN7TAMorh/d1337JKA5Tsw?invite=cr-MSxVTHosNzgzNTk5MDUs

I'm up2date with the full QBCore.

**Comment by Z3rio** [comment]
> I'm having this issue too. Tried to empty my data cache but without luck. https://medal.tv/games/gta-v/clips/BJOIHN7TAMorh/d1337JKA5Tsw?invite=cr-MSxVTHosNzgzNTk5MDUs
> 
> I'm up2date with the full QBCore.

Please dont cross comment, this issue is outdated (posted nearly half a year ago).
Even if you are having this issue at this moment, it doesnt apply to this issue thread since this issue was from a entirely different version of qb-multicharacter.
Thank you.
