### ISSUE TITLE
[BUG] No character clothing customization on first creation 

### ISSUE THREAD

**Issue by justinfurnas** [qbcore-framework/qb-multicharacter#99]
There doesn't appear to be a way to customize your characters appearance and clothing when creating a new character.

**Comment by tom-osborne** [comment]
> There doesn't appear to be a way to customize your characters appearance and clothing when creating a new character.

@justinfurnas after you create your character it should load you into your apartment and give you the clothing/character creation menu.

Please can you confirm whether you have any errors in your client or server console when creating a character?
